{{- if .Values.tokenInfoExtractor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: token-info-{{ include "blockscout-admin.fullname" . }}-config
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
data:
  networks.json: |
    {
      "networks": {
        {{- $len := len .Values.config.network }}
        {{- range $i, $value := .Values.config.network }}
        "{{ .id }}": {
          "default_chain_name": "{{ .name }}"
        }{{- if ne (sub $len 1) $i }},{{- end }}
       {{- end }}
      }
    }
{{- end }}
