apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: websocket
      protocol: TCP
      name: websocket
    - port: 8020
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}
