apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout-proxy-verifier.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    {{- include "blockscout-proxy-verifier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxyVerifier.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/blockscout-proxy-verifier-secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        {{- include "blockscout-proxy-verifier.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blockscout-proxy-verifier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxyVerifier.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.proxyVerifier.securityContext | nindent 12 }}
          image: "{{ .Values.proxyVerifier.image.repository }}:{{ .Values.proxyVerifier.image.tag }}"
          resources:
            {{- toYaml .Values.proxyVerifier.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.proxyVerifier.image.pullPolicy }}
          {{- with .Values.proxyVerifier.command }}
          command:  {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.proxyVerifier.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8050
              protocol: TCP
            - name: metrics
              containerPort: 6060
              protocol: TCP
          env:
            {{- if .Values.proxyVerifier.serviceMonitor.enabled }}
            - name: PROXY_VERIFIER__METRICS__ENABLED
              value: 'true'
            {{- end }}
            {{- range $key, $value := .Values.proxyVerifier.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "blockscout-proxy-verifier.fullname" . }}-env
          {{- if .Values.proxyVerifier.files.enabled }}
          {{- $fullName := include "blockscout-proxy-verifier.fullname" . }}
          {{- $mountPath := .Values.proxyVerifier.files.mountPath }}
          volumeMounts:
            {{- range $key, $value := .Values.proxyVerifier.files.list }}
            - mountPath: {{ $mountPath }}/{{ $key }}
              name: {{ $fullName }}-configmap
              subPath: {{ $key }}
            {{- end }}
          {{- end }}
          {{- if .Values.proxyVerifier.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.proxyVerifier.readinessProbe.path }}
              port: http
              scheme: HTTP
            {{- with .Values.proxyVerifier.readinessProbe.params }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.proxyVerifier.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.proxyVerifier.livenessProbe.path }}
              port: http
              scheme: HTTP
            {{- with .Values.proxyVerifier.livenessProbe.params }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if .Values.proxyVerifier.files.enabled }}
      volumes:
        - configMap:
            name: {{ include "blockscout-proxy-verifier.fullname" . }}-configmap
            defaultMode: 0777
          name: {{ include "blockscout-proxy-verifier.fullname" . }}-configmap
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxyVerifier.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
