apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-proxy-verifier.fullname" . }}-env
  labels:
    {{- include "blockscout-proxy-verifier.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.proxyVerifier.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
