{{- if not .Values.config.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scoutcloud.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scoutcloud.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.config.database.username | b64enc | quote }}
  password: {{ .Values.config.database.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scoutcloud.fullname" . }}-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scoutcloud.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.github.token | b64enc | quote }}
