{{- if .Values.config.jwtsecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rpc-node.fullname" . }}-jwtsecret
  labels:
    {{- include "rpc-node.labels" . | nindent 4 }}
type: Opaque
data:
  jwtsecret: {{ .Values.config.jwtsecret.value | b64enc }}
{{- end }}
