{{- if and .Values.consensus.enabled .Values.consensus.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rpc-node.fullname" . }}-consensus-env
  labels:
    {{- include "rpc-node.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.consensus.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
